# Generated by Django 4.2.30 on 2026-05-11 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('committee_type', models.CharField(choices=[('specification', 'Specification'), ('evaluation', 'Evaluation'), ('review', 'Review'), ('contract', 'Contract'), ('other', 'Other')], max_length=50)),
                ('formation_date', models.DateField(blank=True, null=True)),
                ('specification_submission_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('should_notify', models.BooleanField(default=False)),
                ('formation_letter', models.FileField(blank=True, null=True, upload_to='formation_letters/')),
                ('approval_status', models.CharField(default='active', max_length=50)),
                ('assigned_date', models.DateField(blank=True, help_text='Date when committee was assigned to procurement plan', null=True)),
                ('completion_date', models.DateField(blank=True, help_text='Date when committee completed their work', null=True)),
                ('technical_evaluation_completion_date', models.DateField(blank=True, help_text='Date when technical evaluation was completed', null=True)),
                ('financial_evaluation_completion_date', models.DateField(blank=True, help_text='Date when financial evaluation was completed', null=True)),
                ('decision_date', models.DateField(blank=True, help_text='Date when final committee decision was reached', null=True)),
                ('committee_status', models.CharField(choices=[('assigned', 'Assigned'), ('active', 'Active'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('dissolved', 'Dissolved')], default='assigned', help_text='Current status of the committee in its lifecycle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('specification_title', models.CharField(blank=True, max_length=255, null=True)),
                ('specification_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_role', models.CharField(default='member', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCommitteeDefaultMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_role', models.CharField(default='member', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['committee_role', 'created_at'],
            },
        ),
    ]
