# Generated by Django 4.2.30 on 2026-05-11 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('committee', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcommitteedefaultmember',
            name='office',
            field=models.ForeignKey(blank=True, help_text='If set, this default applies only to the specified office (and its subtree). If null, it is a global fallback.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_review_members', to='users.office'),
        ),
        migrations.AddField(
            model_name='reviewcommitteedefaultmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_review_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='committee.committee'),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committee',
            name='procurement_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees', to='procurement.procurementplan'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewcommitteedefaultmember',
            unique_together={('user', 'committee_role', 'office')},
        ),
        migrations.AlterUniqueTogether(
            name='committeemembership',
            unique_together={('committee', 'user')},
        ),
    ]
