# Generated by Django 4.2.30 on 2026-05-11 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('committee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees', to='users.office'),
        ),
    ]
