# Generated by Django 4.2.30 on 2026-05-15 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committee', '0003_committee_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='current_phase',
            field=models.CharField(choices=[('initialization', 'Initialization'), ('finalization', 'Finalization')], default='initialization', help_text='Current phase of the committee lifecycle', max_length=20),
        ),
        migrations.CreateModel(
            name='CommitteePhaseCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('initialization', 'Initialization'), ('finalization', 'Finalization')], help_text='Which phase this checkpoint belongs to', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='committee.committee')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checkpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['phase', 'order', 'created_at'],
                'indexes': [models.Index(fields=['committee', 'phase'], name='committee_c_committ_6f0e5f_idx'), models.Index(fields=['committee', 'is_completed'], name='committee_c_committ_41637c_idx')],
                'unique_together': {('committee', 'phase', 'order')},
            },
        ),
    ]
