# Generated by Django 4.2.30 on 2026-06-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_committee_current_phase_committeephasecheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['committee', 'is_active'], name='committee_c_committ_218c72_idx'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['user', 'is_active'], name='committee_c_user_id_3e1387_idx'),
        ),
    ]
