# Generated by Django 4.2.30 on 2026-06-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0006_add_committee_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Remarks entered when marking the committee as completed', null=True),
        ),
    ]
