# Generated by Django 4.2.30 on 2026-05-11 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('committee', '0002_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='procurement_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='procurement.procurementplan'),
        ),
        migrations.AddField(
            model_name='quarterlytarget',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this target as completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_quarterly_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarterlytarget',
            name='procurement_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_targets', to='procurement.procurementplan'),
        ),
        migrations.AddField(
            model_name='procurementstakeholder',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned this stakeholder role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stakeholders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementstakeholder',
            name='escalation_contact',
            field=models.ForeignKey(blank=True, help_text='Who to contact if this stakeholder is unavailable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_for_stakeholders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementstakeholder',
            name='procurement_plan',
            field=models.ForeignKey(help_text='The procurement plan this stakeholder is involved in', on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='procurement.procurementplan'),
        ),
        migrations.AddField(
            model_name='procurementstakeholder',
            name='user',
            field=models.ForeignKey(help_text='The user assigned as stakeholder', on_delete=django.db.models.deletion.CASCADE, related_name='procurement_stakeholder_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementrisk',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementrisk',
            name='procurement_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='procurement.procurementplan'),
        ),
        migrations.AddField(
            model_name='procurementplan',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='committee.committee'),
        ),
        migrations.AddField(
            model_name='procurementplan',
            name='office',
            field=models.ForeignKey(blank=True, help_text='The office this procurement plan belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_plans', to='users.office'),
        ),
        migrations.AddField(
            model_name='procurementplan',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementnotification',
            name='procurement_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='procurement.procurementplan'),
        ),
        migrations.AddField(
            model_name='procurementnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='last_accessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_accessed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='procurement.procurementdocument'),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='procurement_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='procurement.procurementplan'),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantermination',
            name='procurement_plan',
            field=models.OneToOneField(help_text='The procurement plan that was terminated', on_delete=django.db.models.deletion.CASCADE, related_name='termination', to='procurement.procurementplan'),
        ),
        migrations.AddField(
            model_name='plantermination',
            name='terminated_by',
            field=models.ForeignKey(help_text='User who terminated the plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='measured_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded this measurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measured_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User responsible for this metric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='procurement_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='procurement.procurementplan'),
        ),
        migrations.AddField(
            model_name='documentapprovalworkflow',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentapprovalworkflow',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='procurement.procurementdocument'),
        ),
        migrations.AddField(
            model_name='documentapprovalstep',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_approval_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentapprovalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procurement.documentapprovalworkflow'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='procurement.procurementdocument'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflowdependency',
            name='from_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_sources', to='procurement.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalworkflowdependency',
            name='to_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_targets', to='procurement.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='User responsible for this approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='backup_approver',
            field=models.ForeignKey(blank=True, help_text='Backup approver if primary is unavailable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_approval_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='delegated_to',
            field=models.ForeignKey(blank=True, help_text='User this approval has been delegated to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Other approvals that must be completed first', related_name='dependents', through='procurement.ApprovalWorkflowDependency', to='procurement.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='escalated_to',
            field=models.ForeignKey(blank=True, help_text='User this approval has been escalated to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='procurement_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='procurement.procurementplan'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='procurement_plan',
            field=models.ForeignKey(help_text='The procurement plan this activity relates to', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='procurement.procurementplan'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together={('procurement_plan', 'stage')},
        ),
        migrations.AlterUniqueTogether(
            name='quarterlytarget',
            unique_together={('procurement_plan', 'quarter')},
        ),
        migrations.AddIndex(
            model_name='procurementstakeholder',
            index=models.Index(fields=['procurement_plan', 'role'], name='procurement_procure_046a98_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementstakeholder',
            index=models.Index(fields=['user', 'status'], name='procurement_user_id_d672bf_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementstakeholder',
            index=models.Index(fields=['involvement_level', 'primary_contact'], name='procurement_involve_f9dcaa_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementstakeholder',
            index=models.Index(fields=['assigned_at', 'status'], name='procurement_assigne_09fee4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procurementstakeholder',
            unique_together={('procurement_plan', 'user', 'role')},
        ),
        migrations.AddIndex(
            model_name='procurementnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='procurement_recipie_8a4be1_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementnotification',
            index=models.Index(fields=['procurement_plan', 'notification_type'], name='procurement_procure_20e247_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementnotification',
            index=models.Index(fields=['sent_at', 'is_read'], name='procurement_sent_at_53a669_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementdocument',
            index=models.Index(fields=['procurement_plan', 'document_type'], name='procurement_procure_51da4b_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementdocument',
            index=models.Index(fields=['status', 'created_at'], name='procurement_status_3f640e_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['procurement_plan', 'metric_type'], name='procurement_procure_f2fed6_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['measurement_date', 'status'], name='procurement_measure_17a189_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['owner', 'status'], name='procurement_owner_i_0a12cf_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['next_measurement_due'], name='procurement_next_me_560998_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancemetric',
            unique_together={('procurement_plan', 'metric_type', 'measurement_date')},
        ),
        migrations.AlterUniqueTogether(
            name='documentapprovalstep',
            unique_together={('workflow', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['document', 'timestamp'], name='procurement_documen_f5457a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['user', 'action'], name='procurement_user_id_af7c3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflowdependency',
            unique_together={('from_workflow', 'to_workflow')},
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['procurement_plan', 'status'], name='procurement_procure_249c24_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['approver', 'status'], name='procurement_approve_553bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['due_date', 'status'], name='procurement_due_dat_d84ee2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflow',
            unique_together={('procurement_plan', 'approval_type', 'sequence_order')},
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['procurement_plan', '-timestamp'], name='procurement_procure_bf10d5_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='procurement_user_id_67a07b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-timestamp'], name='procurement_action_0b0d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='procurement_timesta_92096b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['content_type', 'object_id'], name='procurement_content_a35c24_idx'),
        ),
    ]
