# Generated by Django 4.2.30 on 2026-05-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementstakeholder',
            options={'ordering': ['contact_priority', 'role', 'user__employee_profile__name'], 'verbose_name': 'Procurement Stakeholder', 'verbose_name_plural': 'Procurement Stakeholders'},
        ),
    ]
