# Generated by Django 4.2.30 on 2026-05-11 04:56

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_office', models.CharField(max_length=255)),
                ('directorate_id', models.IntegerField(blank=True, null=True)),
                ('ac_office_id', models.IntegerField(blank=True, null=True)),
                ('cc_office_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_working_office',
                'ordering': ['name_of_office'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, default='Engineer', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('otp_enabled', models.BooleanField(default=False)),
                ('reset_token', models.CharField(blank=True, max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'users_customuser',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('seniority', models.DateTimeField(blank=True, null=True)),
                ('retirement', models.DateTimeField(blank=True, null=True)),
                ('mno', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, unique=True)),
                ('permissions', models.JSONField(default=list)),
                ('restricted_to', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(choices=[('user_management', 'User Management'), ('settings', 'System Settings'), ('planning', '1. Planning'), ('specification', '2. Specification'), ('spec_review', '3. Specification Review'), ('tender', '4. Tender'), ('evaluation', '5. Evaluation'), ('letters', '6. LOI / LOA'), ('contract', '7. Contract Preparation'), ('bidding', '8. Bidders & Bids'), ('reports', 'Reports & Analytics')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users_permission',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('level', models.IntegerField(default=0)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('post_alias', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users_position',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('modified', 'Modified'), ('bulk_update', 'Bulk Update')], max_length=20)),
                ('permission', models.CharField(max_length=100)),
                ('old_permissions', models.JSONField(blank=True, default=list)),
                ('new_permissions', models.JSONField(blank=True, default=list)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs', to='users.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.office')),
            ],
            options={
                'db_table': 'users_procurement_office',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.office'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.position'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.ForeignKey(blank=True, db_column='user_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='working_office',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.workingoffice'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role')),
            ],
            options={
                'db_table': 'users_rolepermission',
                'ordering': ['role', 'permission__group', 'permission__name'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('seq_no', models.CharField(max_length=50)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password Reset')], default='login', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired'), ('invalidated', 'Invalidated')], default='sent', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='users_otplo_user_id_ba92d6_idx'), models.Index(fields=['seq_no'], name='users_otplo_seq_no_1395ec_idx')],
            },
        ),
    ]
