# Generated by Django 4.2.30 on 2026-05-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_and_office_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_directorate',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='office',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='office',
            name='parent',
        ),
        migrations.AddField(
            model_name='department',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='users.directorate'),
        ),
        migrations.AddField(
            model_name='office',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices', to='users.directorate'),
        ),
    ]
