# Generated by Django 4.2.30 on 2026-05-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_directorate_remove_office_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='department',
        ),
    ]
