# Generated by Django 4.2.30 on 2026-05-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_office_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorate',
            name='code',
        ),
    ]
