# Generated by Django 4.2.30 on 2026-05-15 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_directorate_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='working_office',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='email',
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='designation',
            field=models.CharField(blank=True, default='Engineer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
