# Generated by Django 4.2.30 on 2026-05-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
