# Generated by Django 4.2.30 on 2026-06-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_employeedetail_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpEmployeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('middle_names', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=80, null=True)),
                ('grade', models.CharField(blank=True, max_length=240, null=True)),
                ('seniority_date', models.DateField(blank=True, null=True)),
                ('job_id', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('job_name', models.CharField(blank=True, max_length=700, null=True)),
                ('work_org_id', models.CharField(blank=True, max_length=150, null=True)),
                ('work_office', models.CharField(blank=True, max_length=240, null=True)),
                ('mobile', models.CharField(blank=True, max_length=60, null=True)),
                ('email_address', models.CharField(blank=True, max_length=240, null=True)),
            ],
            options={
                'db_table': 'employee_erp_record_master',
                'ordering': ['empno'],
                'managed': False,
            },
        ),
    ]
